name: Scrape Nesine Odds

on:
  workflow_dispatch:
  push:
    paths:
      - main.py

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Repo-nu klonla
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Playwright və tələbləri quraşdır
      run: |
        pip install -r requirements.txt
        playwright install

    - name: Skripti işə sal
      run: python main.py
