name: Run Scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu yüklə
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Python kitabxanalarını quraşdır
      run: pip install requests beautifulsoup4

    - name: Scraper-i işə sal
      run: python main.py
