name: Scrape Betway Odds

on:
  workflow_dispatch:
  push:
    paths:
      - main.py
      - requirements.txt

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Repo-nu klonla
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Kitabxanaları yüklə
      run: |
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Python skriptini işə sal
      run: python main.py
